# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# title: Điện lạnh Anh Dũng
# email: dienlanhanhdung_lqd@gmail.com
# description: >- # this means to ignore newlines until "baseurl:"
#   Chuyên bán và sửa chữa tủ lạnh, máy lạnh và máy giặt. Nhận vệ sinh và bảo trì 24/7 với giá cả phải chăng, cam kết linh kiện chính hãng.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://dienlanhanhdung.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: dienlanhanhdung
# github_username:  dienlanhanhdung
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-textile-converter
  - jekyll-sitemap
  - jekyll-compose
  - jekyll-youtube
  - jekyll-timeago
  - jekyll-toc
  - jekyll-email-protect
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

